const unidadData = {
    unidad_idUnidad: "",
    unidad_idEmpresa: "",
    unidad_numeroComercial: "",
    unidad_estatus: 1,
    unidad_idModeloVehiculo: 0,
    unidad_placa: "",
    unidad_capacidad: "",
    unidad_NumSerie: "",
    unidad_AreaFuncional: "",
    unidad_Poliza: "",
    unidad_TarjetaC: "",
    unidad_CartaFactura: "",
    unidad_NumeroComputadora: "",
    unidad_idTipoServicio: '',
    unidad_permisoCRE:'',
    unidad_marca: '',
    unidad_año: '',
    unidad_modelo:'',
    unidad_Cilindros: "",
    unidad_NumEcon: "",
}

export default unidadData;

export const unidadValidations = {
    // unidad_idEmpresa: 'required',
    unidad_numeroComercial: 'required',
    unidad_estatus: 'required',
    unidad_capacidad: 'required',
    unidad_AreaFuncional: 'required',
    unidad_idTipoServicio: 'required',
    unidad_permisoCRE: 'required',
    unidad_marca: 'required',
    unidad_año: 'required', 
    unidad_modelo: 'required',
    // unidad_placa: 'required',
    // unidad_NumSerie: 'required',
    unidad_Cilindros: 'required',
    // unidad_Poliza: 'required',
    // unidad_TarjetaC: 'required',
    // unidad_CartaFactura: 'required',
    // unidad_NumeroComputadora: 'required',

}

export const unidadFields = {
    unidad_idUnidad: 'id',
    unidad_idEmpresa: 'empresa',
    unidad_numeroComercial: 'numero comercial',
    unidad_estatus: 'estatus',
    unidad_idModeloVehiculo: 'modelo',
    unidad_placa: 'placa',
    unidad_capacidad: 'capacidad',
    unidad_NumSerie: 'numero de serie',
    unidad_AreaFuncional: 'area funcional',
    unidad_Poliza: 'poliza',
    unidad_TarjetaC: 'tarjeta circulacion',
    unidad_CartaFactura: 'factura',
    unidad_NumeroComputadora: 'no. computadora',
    unidad_idTipoServicio: 'Tipo de servicio',
    unidad_permisoCRE: 'permiso cre',
    unidad_NumEcon: 'numero economico',
    unidad_marca: 'marca',
    unidad_modelo: 'modelo',
    unidad_año: 'año',
    unidad_Cilindros: 'cilindros',

}