import moment from "moment"

const personData = {
    IdPersona:"",
    IdMunicipio: "",
    IdEstado: "",
    IdDepto: "",
    IdPuesto: "",
    IdCedis: "",
    IdZona: "",
    IdCentroCostos: "",
    IdChecador: "",
    IdColonia: "",
    Nombres: "",
    ApePat: "",
    ApeMat: "",
    Calle: "",
    CasaNum: "",
    Tel1: "",
    Tel2: "",
    Tel3: "",
    Tel1Owner: "",
    Tel2Owner: "",
    Tel3Owner: "",
    EstadoCivil: "",
    FechaNacimiento: "",
    FechaIngreso: moment().format('YYYY-MM-DD'),
    // FechaIngresoIMSS: new Date(),
    Nacionalidad: "",
    Sexo: "",
    NSS: "",
    RFC: "",
    Curp: "",
    CodigoPostal: "",
    PeriodoNominal: "",
    SalarioDiario: "",
    SalarioReal: "",
    CreditoInfonavit: "",
    DescuentoInfonavit: "",
    CantidadDescuento: "",
    TipoEmpleado: "",
    ContratoTipo: "",
    TieneSeguro: false,
    EsEmpleado: true,
    TieneInfonavit: false,
    ExcepcionChecador: false,
    fotoEmpleado: "",
    AsignarActivos: false,
    Celular: '',
}

export const personValidations = {
    IdMunicipio: 'required',
    IdEstado: 'required',
    IdDepto: 'required',
    IdPuesto: 'required',
    IdCedis: 'required',
    IdZona: 'required',
    // IdCentroCostos: 'required',
    // IdChecador: 'required',
    IdColonia: 'required',
    Nombres: 'required',
    ApePat: 'required',
    ApeMat: 'required',
    Calle: 'required',
    // CasaNum: 'required',
    Tel1: 'required',
    // Tel2: 'required',
    // Tel3: 'required',
    Tel1Owner: 'required',
    // Tel2Owner: 'required',
    // Tel3Owner: 'required',
    EstadoCivil: 'required',
    FechaNacimiento: 'required',
    FechaIngreso: 'required',
    // FechaIngresoIMSS: 'required',
    Nacionalidad: 'required',
    Sexo: 'required',
    NSS: 'required',
    RFC: 'required',
    Curp: 'required',
    CodigoPostal: 'required',
    PeriodoNominal: 'required',
    SalarioDiario: 'required',
    SalarioReal: 'required',
    TipoEmpleado: 'required',
    ContratoTipo: 'required',
};

export const personFields = {
    IdMunicipio: 'municipio',
    IdEstado: 'estado',
    IdDepto: 'departamento',
    IdPuesto: 'puesto',
    IdCedis: 'cedis',
    IdZona: 'zona',
    // IdCentroCostos: 'centro de costos',
    IdChecador: 'checador',
    IdColonia: 'colonia',
    Nombres: 'nombres',
    ApePat: 'apellido paterno',
    ApeMat: 'apellido materno',
    Calle: 'calle',
    CasaNum: 'número de casa',
    Tel1: 'teléfono 1',
    Tel2: 'teléfono 2',
    Tel3: 'teléfono 3',
    Tel1Owner: 'dueño teléfono 1',
    Tel2Owner: 'dueño teléfono 2',
    Tel3Owner: 'dueño teléfono 3',
    EstadoCivil: 'estado civil',
    FechaNacimiento: 'fecha de nacimiento',
    FechaIngreso: 'fecha de ingreso',
    FechaIngresoIMSS: 'fecha de ingreso imss',
    Nacionalidad: 'nacionalidad',
    Sexo: 'sexo',
    NSS: 'número de seguro social',
    RFC: 'rfc',
    Curp: 'curp',
    CodigoPostal: 'código postal',
    PeriodoNominal: 'periodo nominal',
    SalarioDiario: 'salario diario',
    SalarioReal: 'salario real',
    TipoEmpleado: 'tipo de empleado',
    ContratoTipo: 'tipo de contrato',
};

export default personData

export const IntStateDialogPerson = {
    loading: false,
    largeDialog: false,
    specialPermission: false,
    action: '',
    showForm: false,
    title: "Detalles"
}