export const EmpresaData = {
      empresa_razonSocial: '',
      empresa_razonComercial: '',
      empresa_calle: '',
      empresa_colonia: '',
      empresa_ciudad: '',
      empresa_localidad: '',
      empresa_numeroExterior: '',
      empresa_numeroInterior: '',
      empresa_idPais: '',
      empresa_idEstado: '',
      empresa_codigoPostal: '',
      empresa_rfc: '',
      empresa_idRegimenFiscal: '',
      empresa_referencia: '',
      empresa_telefonos: '',
      empresa_numeroPermiso: '',
      empresa_numeroOficio: '',
      empresa_passwordSello: '',
      empresa_usuarioCertificado: '',
      empresa_passwordCertificado: '',
      empresa_Color: '#00000',
      empresa_noCertificado: '',
      empresa_ConsultaRemision: 0,
      empresa_microsip: '',
      empresa_siaf: '',
      empresa_regimenCapital: '',
      empresa_permisoCRE: '',
      empresa_SelloDigital: '',
      empresa_archivoKey: '',
      empresa_Logotipo: '',
      empresa_host:'',
      empresa_correoNotificacion:'',
      empresa_passwordCorreo:'',
      empresa_puerto: '',
      empresa_seguridadSSL:''

}

export const CuentasBanco = {
      CuentasBancoEmpresa_idBancoEmpresa: '',
      CuentasBancoEmpresa_idBancoEmpresa: '',
      CuentasBancoEmpresa_idEmpresa: '',
      CuentasBancoEmpresa_idBanco: '',
      CuentasBancoEmpresa_Descripcion: '',
      CuentasBancoEmpresa_Cuenta: '',
      CuentasBancoEmpresa_Estatus: '0',
}

export const empresaValidations = {
      empresa_razonSocial: 'required',
      empresa_razonComercial: 'required',
      empresa_calle: 'required',
      empresa_colonia: 'required',
      empresa_ciudad: 'required',
      empresa_localidad: 'required',
      empresa_numeroExterior: 'required',
      empresa_numeroInterior: '',
      empresa_idPais: 'required',
      empresa_idEstado: 'required',
      empresa_codigoPostal: 'required',
      empresa_rfc: ['required', 'rfc'],
      empresa_idRegimenFiscal: 'required',
      empresa_referencia: '',
      empresa_telefonos: 'required',
      empresa_numeroPermiso: 'required',
      empresa_numeroOficio: 'required',
      empresa_passwordSello: 'required',
      empresa_usuarioCertificado: 'required',
      empresa_passwordCertificado: 'required',
      empresa_Color: '',
      empresa_noCertificado: 'required',
      empresa_ConsultaRemision: 'required',
      empresa_microsip: '',
      empresa_siaf: '',
      empresa_regimenCapital: '',
      empresa_permisoCRE: '',

};

export const initialState = {
      empresa: EmpresaData,
      cuentasBanco: CuentasBanco,
      cuentasBancoList: null,
      timbres: '',
      loading: {
          openModal: false,
          form: false
      },
      open: false,
      action: '',
      regimens: null,
      image: null,
      archivos: null,
      errors: {},
      step: 0,
      catalog: {
          BANKS: [],
          EMPRESAS: [],
          // Tomar en cuenta que las acciones se usan para el titulo de detalles dialog
          ACTION: {
              TIMBRES: "Timbres",
              ADD_BANK_COUNT: "Crear cuenta de banco",
              EDIT_BANK_COUNT: "Editar cuentas de banco",
              CREATE: 'Crear empresa',
              EDIT: "Editar empresa",
              CORREOS: "Configuración de correos",
          },
      },
      aux: '',
      fotoEmpleado: '',
      submit: false,
      submitCuenta: false,
      getCuentasBandoList: false,
      confirmacionDialog: {
        show: false,
        confirm: false,
        back: false
    }
  }